// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: schoolevents.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RegionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique ID for the object.
	Registered  *Registered  `protobuf:"bytes,2,opt,name=registered,proto3" json:"registered,omitempty"`
	Renamed     *Renamed     `protobuf:"bytes,3,opt,name=renamed,proto3" json:"renamed,omitempty"`
	Activated   *Activated   `protobuf:"bytes,4,opt,name=activated,proto3" json:"activated,omitempty"`
	Deactivated *Deactivated `protobuf:"bytes,5,opt,name=deactivated,proto3" json:"deactivated,omitempty"`
}

func (x *RegionEvent) Reset() {
	*x = RegionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionEvent) ProtoMessage() {}

func (x *RegionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionEvent.ProtoReflect.Descriptor instead.
func (*RegionEvent) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{0}
}

func (x *RegionEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegionEvent) GetRegistered() *Registered {
	if x != nil {
		return x.Registered
	}
	return nil
}

func (x *RegionEvent) GetRenamed() *Renamed {
	if x != nil {
		return x.Renamed
	}
	return nil
}

func (x *RegionEvent) GetActivated() *Activated {
	if x != nil {
		return x.Activated
	}
	return nil
}

func (x *RegionEvent) GetDeactivated() *Deactivated {
	if x != nil {
		return x.Deactivated
	}
	return nil
}

type SchoolEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique ID for the object.
	Registered  *Registered  `protobuf:"bytes,2,opt,name=registered,proto3" json:"registered,omitempty"`
	Renamed     *Renamed     `protobuf:"bytes,3,opt,name=renamed,proto3" json:"renamed,omitempty"`
	Activated   *Activated   `protobuf:"bytes,4,opt,name=activated,proto3" json:"activated,omitempty"`
	Deactivated *Deactivated `protobuf:"bytes,5,opt,name=deactivated,proto3" json:"deactivated,omitempty"`
	Placed      *Placed      `protobuf:"bytes,6,opt,name=placed,proto3" json:"placed,omitempty"`
}

func (x *SchoolEvent) Reset() {
	*x = SchoolEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchoolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolEvent) ProtoMessage() {}

func (x *SchoolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolEvent.ProtoReflect.Descriptor instead.
func (*SchoolEvent) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{1}
}

func (x *SchoolEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SchoolEvent) GetRegistered() *Registered {
	if x != nil {
		return x.Registered
	}
	return nil
}

func (x *SchoolEvent) GetRenamed() *Renamed {
	if x != nil {
		return x.Renamed
	}
	return nil
}

func (x *SchoolEvent) GetActivated() *Activated {
	if x != nil {
		return x.Activated
	}
	return nil
}

func (x *SchoolEvent) GetDeactivated() *Deactivated {
	if x != nil {
		return x.Deactivated
	}
	return nil
}

func (x *SchoolEvent) GetPlaced() *Placed {
	if x != nil {
		return x.Placed
	}
	return nil
}

type Registered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *Registered) Reset() {
	*x = Registered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{2}
}

func (x *Registered) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Registered) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type Renamed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Renamed) Reset() {
	*x = Renamed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Renamed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renamed) ProtoMessage() {}

func (x *Renamed) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renamed.ProtoReflect.Descriptor instead.
func (*Renamed) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{3}
}

func (x *Renamed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//   activate
type Activated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Activated) Reset() {
	*x = Activated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activated) ProtoMessage() {}

func (x *Activated) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activated.ProtoReflect.Descriptor instead.
func (*Activated) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{4}
}

//   deactivate
type Deactivated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Deactivated) Reset() {
	*x = Deactivated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deactivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deactivated) ProtoMessage() {}

func (x *Deactivated) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deactivated.ProtoReflect.Descriptor instead.
func (*Deactivated) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{5}
}

//   if we need a place name to further specify a school
type Placed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Town string `protobuf:"bytes,2,opt,name=town,proto3" json:"town,omitempty"`
}

func (x *Placed) Reset() {
	*x = Placed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schoolevents_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Placed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placed) ProtoMessage() {}

func (x *Placed) ProtoReflect() protoreflect.Message {
	mi := &file_schoolevents_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placed.ProtoReflect.Descriptor instead.
func (*Placed) Descriptor() ([]byte, []int) {
	return file_schoolevents_proto_rawDescGZIP(), []int{6}
}

func (x *Placed) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

var File_schoolevents_proto protoreflect.FileDescriptor

var file_schoolevents_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x52, 0x07, 0x72, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x2e, 0x0a, 0x0b, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x64, 0x52, 0x0b, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x22,
	0xe9, 0x01, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2b, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x07,
	0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x52, 0x07, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x52,
	0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x0b, 0x64, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x52, 0x0b, 0x64,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x64, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64,
	0x22, 0x1c, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f,
	0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x77, 0x6e, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schoolevents_proto_rawDescOnce sync.Once
	file_schoolevents_proto_rawDescData = file_schoolevents_proto_rawDesc
)

func file_schoolevents_proto_rawDescGZIP() []byte {
	file_schoolevents_proto_rawDescOnce.Do(func() {
		file_schoolevents_proto_rawDescData = protoimpl.X.CompressGZIP(file_schoolevents_proto_rawDescData)
	})
	return file_schoolevents_proto_rawDescData
}

var file_schoolevents_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_schoolevents_proto_goTypes = []interface{}{
	(*RegionEvent)(nil), // 0: RegionEvent
	(*SchoolEvent)(nil), // 1: SchoolEvent
	(*Registered)(nil),  // 2: Registered
	(*Renamed)(nil),     // 3: Renamed
	(*Activated)(nil),   // 4: Activated
	(*Deactivated)(nil), // 5: Deactivated
	(*Placed)(nil),      // 6: Placed
}
var file_schoolevents_proto_depIdxs = []int32{
	2, // 0: RegionEvent.registered:type_name -> Registered
	3, // 1: RegionEvent.renamed:type_name -> Renamed
	4, // 2: RegionEvent.activated:type_name -> Activated
	5, // 3: RegionEvent.deactivated:type_name -> Deactivated
	2, // 4: SchoolEvent.registered:type_name -> Registered
	3, // 5: SchoolEvent.renamed:type_name -> Renamed
	4, // 6: SchoolEvent.activated:type_name -> Activated
	5, // 7: SchoolEvent.deactivated:type_name -> Deactivated
	6, // 8: SchoolEvent.placed:type_name -> Placed
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_schoolevents_proto_init() }
func file_schoolevents_proto_init() {
	if File_schoolevents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schoolevents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schoolevents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchoolEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schoolevents_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schoolevents_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Renamed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schoolevents_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schoolevents_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deactivated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schoolevents_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Placed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schoolevents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schoolevents_proto_goTypes,
		DependencyIndexes: file_schoolevents_proto_depIdxs,
		MessageInfos:      file_schoolevents_proto_msgTypes,
	}.Build()
	File_schoolevents_proto = out.File
	file_schoolevents_proto_rawDesc = nil
	file_schoolevents_proto_goTypes = nil
	file_schoolevents_proto_depIdxs = nil
}
